### ISSUE TITLE
0.27.0-RC1 artifacts require Java 11

### ISSUE THREAD

**Issue by djspiewak** [com-lihaoyi/utest#226]
```
  java.lang.UnsupportedClassVersionError: utest/EnableReflectiveInstantiation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    java.lang.ClassLoader.defineClass1(ClassLoader.java:-2)
    java.lang.ClassLoader.defineClass(ClassLoader.java:756)
    java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    java.security.AccessController.doPrivileged(AccessController.java:-2)
    java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:102)
    java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    utest.PortableScalaReflectExcerpts$.l$1(PortableScalaReflectExcerpts.scala:47)
    utest.PortableScalaReflectExcerpts$.c$2$$anonfun$1(PortableScalaReflectExcerpts.scala:44)
    dotty.runtime.function.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
    scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:446)
    utest.PortableScalaReflectExcerpts$.c$1(PortableScalaReflectExcerpts.scala:44)
    utest.PortableScalaReflectExcerpts$.inheritsAnnotation(PortableScalaReflectExcerpts.scala:56)
    utest.PortableScalaReflectExcerpts$.load(PortableScalaReflectExcerpts.scala:24)
    utest.PortableScalaReflectExcerpts$.lookupLoadableModuleClass(PortableScalaReflectExcerpts.scala:15)
    utest.PlatformShims$.loadModule(PlatformShims.scala:14)
    utest.runner.BaseRunner.$anonfun$3(BaseRunner.scala:108)
```

I get the above error whenever I attempt to use µTest 0.7.5 from Dotty 0.27.0-RC1 (the 2.12 and 2.13 artifacts do not exhibit this issue).

**Comment by darkfrog26** [comment]
@lihaoyi, I think this is the same problem seen here: https://github.com/lihaoyi/geny/pull/17

**Comment by darkfrog26** [comment]
@lihaoyi I believe this is the lynchpin keeping `geny` from releasing, that is keeping `upickle` from releasing, that is keeping `profig` from releasing, that is keeping `scribe` from releasing. I would be happy to take a look and see if I can figure out why this is happening, but I'm not at all familiar with Mill.

**Comment by anatoliykmetyuk** [comment]
The problem arises because utest & sourcecode for Scala 3 were published for Java 11 by mistake. The solution is either to bump the version of these two libs and release them for Java 8, or wait a couple of weeks until Scala 3 RC1 is here, and release these libs for RC1 under Java 8.

**Comment by darkfrog26** [comment]
@anatoliykmetyuk can anyone but @lihaoyi do another release?

**Comment by anatoliykmetyuk** [comment]
I can publish a release once @lihaoyi advises on how we should proceed with it.

**Comment by lihaoyi** [comment]
Feel free to bump a version and republish everything

**Comment by darkfrog26** [comment]
@anatoliykmetyuk any idea when you'll be able to get to this?

**Comment by anatoliykmetyuk** [comment]
I'm on vacation for the next two weeks, so I can look into it at the beginning of February. But then, we would probably have another release of Dotty, so, if nobody tags the new version by that time, we won't need to tag a new version.

**Comment by darkfrog26** [comment]
Is there anything I can do to expedite this? I can submit a PR if that would help move this along?

**Comment by lolgab** [comment]
Do you still need this?
The latest version was released for Scala `3.0.0-RC1` which is not source-compatible with `0.27.0-RC1`.

**Comment by darkfrog26** [comment]
I don't.

**Comment by lolgab** [comment]
Now that Scala 3 is at LTS `3.3.3` and we dropped old Dotty support I'm closing this issue.
